services:
  traccar:
    image: traccar/traccar:latest
    container_name: traccar
    restart: unless-stopped
    ports:
      - "8083:8082"
      - "5055:5055"
    volumes:
      - ./data:/opt/traccar/data
      - ./logs:/opt/traccar/logs
    environment:
      TZ: America/Sao_Paulo
    labels:
      com.centurylinklabs.watchtower.enable: "true"
