server:
  interface: 127.0.0.1
  port: 5335

  do-ip4: yes
  do-udp: yes
  do-tcp: yes

  # Não escutar IPv6 (evita tentar ::1:53)
  do-ip6: no

  access-control: 127.0.0.1 allow

  hide-identity: yes
  hide-version: yes

  prefetch: yes
  num-threads: 1
